import React from "react";
import FormLayout from "./FormLayout";
import Select from "./MUI/Select";
import { TextField } from "@mui/material";
import Switch from "./MUI/Switch";
export const getFields = ({ formProps, list }) => {
  return [
    {
      span: 1,
      name: "state",
      label: "State",
      type: "select",
      variant: "outlined",
      Component: TextField,
    },
    {
      span: 1,
      name: "city",
      label: "City",
      type: "select",
      variant: "outlined",
      Component: TextField,
    },
    {
      span: 1,
      name: "sectorNumber",
      label: "Location",
      type: "select",
      variant: "outlined",
      Component: TextField,
    },
    {
      span: 1,
      name: "plotNumber",
      label: "Plot Number",
      type: "select",
      variant: "outlined",
      Component: TextField,
    },
    {
      span: 1,
      name: "size",
      label: "Plot Number",
      type: "select",
      variant: "outlined",
      Component: TextField,
    },
    {
      span: 1,
      name: "floor",
      label: "Floor",
      type: "select",
      variant: "outlined",
      Component: TextField,
    },
    {
      span: 1,
      name: "price",
      label: "Price",
      type: "select",
      variant: "outlined",
      Component: TextField,
    },
    {
      span: 1,
      name: "accommodation",
      label: "Accommodation",
      type: "select",
      variant: "outlined",
      Component: TextField,
    },
    {
      span: 1,
      name: "facing",
      label: "Facing",
      type: "select",
      variant: "outlined",
      Component: TextField,
    },
    {
      span: 1,
      name: "parkFacing",
      label: "Park Facing",
      type: "select",
      variant: "outlined",
      Component: TextField,
    },
    {
      span: 1,
      name: "corner",
      label: "Corner",
      type: "select",
      variant: "outlined",
      Component: TextField,
    },
    {
      span: 1,
      name: "possession",
      label: "Possession",
      type: "select",
      variant: "outlined",
      Component: TextField,
    },
    {
      span: 1,
      name: "builderName",
      label: "Builder Name",
      type: "select",
      variant: "outlined",
      Component: TextField,
    },
    {
      span: 1,
      name: "builderContact",
      label: "Builder Contact",
      type: "select",
      variant: "outlined",
      Component: TextField,
    },
    {
      span: 1,
      name: "ownerContact",
      label: "Owner Contact",
      type: "select",
      variant: "outlined",
      Component: TextField,
    },
    {
      span: 1,
      name: "title",
      label: "Primary Title",
      type: "select",
      variant: "outlined",
      Component: TextField,
    },
    {
      span: 1,
      name: "detailTitle",
      label: "Secondary Title",
      type: "select",
      variant: "outlined",
      Component: TextField,
    },
    {
      span: 1,
      name: "description",
      label: "Description",
      type: "select",
      variant: "outlined",
      Component: TextField,
    },
    {
      span: 1,
      name: "thumbnailFile",
      label: "Front (Main) Image",
      type: "select",
      variant: "outlined",
      Component: TextField,
    },
    {
      span: 1,
      name: "normalImageFile",
      label: "More (Normal) Images",
      type: "select",
      variant: "outlined",
      Component: TextField,
    },
    {
      span: 1,
      name: "threeSixtyImages",
      label: "Only 360 Images",
      type: "select",
      variant: "outlined",
      Component: TextField,
    },
    {
      span: 1,
      name: "layoutFile",
      label: "Layout Plan",
      type: "select",
      variant: "outlined",
      Component: TextField,
    },
    {
      span: 1,
      name: "videoFile",
      label: "Load Videos",
      type: "select",
      variant: "outlined",
      Component: TextField,
    },
    {
      span: 1,
      name: "virtualFile",
      label: "Load Virtual Tour",
      type: "select",
      variant: "outlined",
      Component: TextField,
    },
  ];
};
const ListingForm = ({ ...props }) => {
  return <FormLayout getFields={getFields} {...props} />;
};

export default ListingForm;
