import {
    ABOUTUS_SCREEN,
    ACCOUNT_TABS_SCREEN,
    BLOG_SCREEN,
    CARD_DETAILS_SCREEN,
    HOME_SCREEN,
    SEARCH_RESULT,
    AD_MASTER_TABLE,
    MANAGE_USER,
    STATS_LIST,
    APPROVAL_PROPERTIES,
    VIEW_LISTING,
} from "./ScreenJson.js";

export const APP_ROUTES = {
    "/": { key: 'HomeScreen', pagePayload: { key: "HOME_SCREEN", data: HOME_SCREEN } },
    "/login": { key: 'LoginScreen', pagePayload: { key: "HOME_SCREEN", data: HOME_SCREEN } },
    "/searchResult": { key: 'SearchResultScreen', pagePayload: { key: "SEARCH_RESULT", data: SEARCH_RESULT } },
    "/aboutUs": { key: 'AboutUsScreen', pagePayload: { key: "ABOUTUS_SCREEN", data: ABOUTUS_SCREEN } },
    "/blog": { key: 'BlogScreen', pagePayload: { key: "BLOG_SCREEN", data: BLOG_SCREEN } },
    "/:pid": { key: 'PropertyDetailScreen', pagePayload: { key: "CARD_DETAILS_SCREEN", data: CARD_DETAILS_SCREEN } },
    "/account/tabs": { key: 'AccountTabsScreen', pagePayload: { key: "ACCOUNT_TABS_SCREEN", data: ACCOUNT_TABS_SCREEN } },
    "/admin/form": { key: 'FormScreen', pagePayload: { key: "HOME_SCREEN", data: HOME_SCREEN } },
    "/admin/property": { key: 'PropertyManagementScreen', pagePayload: { key: "HOME_SCREEN", data: HOME_SCREEN } },
    "/admin/user": { key: 'UserManagementScreen', pagePayload: { key: "MANAGE_USER", data: MANAGE_USER } },
    "/admin/approveListing": { key: 'ApproveListingScreen', pagePayload: { key: "APPROVAL_PROPERTIES", data: APPROVAL_PROPERTIES } },
    "/admin/master": { key: 'MasterManagementScreen', pagePayload: { key: "HOME_SCREEN", data: HOME_SCREEN } },
    "/admin/masterTable": { key: 'MasterTableScreen', pagePayload: { key: "AD_MASTER_TABLE", data: AD_MASTER_TABLE } },
    "/admin/statistics": { key: 'StatsScreen', pagePayload: { key: "STATS_LIST", data: STATS_LIST } },
    "/admin/statistics/listingData": { key: 'ViewListingScreen', pagePayload: { key: "VIEW_LISTING", data: VIEW_LISTING } },
    "/admin": { key: 'AdminHomeScreen', pagePayload: { key: "HOME_SCREEN", data: HOME_SCREEN } },
};
