import {
    ABOUTUS_SCREEN,
    ACCOUNT_TABS_SCREEN,
    BLOG_SCREEN,
    CARD_DETAILS_SCREEN,
    HOME_SCREEN,
    SEARCH_RESULT,
    AD_MASTER_TABLE,
    MANAGE_USER,
    STATS_LIST,
    APPROVAL_PROPERTIES,
    VIEW_LISTING,
} from "./ScreenJson.js";
import { ABOUT_HERO, API_BUTTON, API_HEADING, AUTO_FETCH_API, AUTO_FETCH_API_POST, AUTO_FETCH_API_USER, BUTTON, CHATBOT, CONTACT_US, CONTAINER, DASHBOARD_LISTING, DETAILED_VIEW, DYNAMIC_CARD_CONTAINER, HAMBURGER_MENU, HEADING, HORIZONTAL_LINE, IMAGE_BANNER, LABEL_MAP, LIST, LOADING, LOGIN_REFRESH, NAVIGATE_BUTTON, OTP_LOGIN, PAGE_FOOTER, PAGE_HEADER, PANEL_HEADER, ROUTE_BUTTON, SCROLL_TO_TOP, SELECT, SELECT2, SELECT_SLIDER, SLIDER, TABLE_HEADER, TABS, TITLE, TOGGLE_BUTTON } from "./components/utils/Const.js";

export const APP_ROUTES = {
    "/": { key: 'HomeScreen', pagePayload: { key: "HOME_SCREEN", data: HOME_SCREEN } },
    "/login": { key: 'LoginScreen', pagePayload: { key: "HOME_SCREEN", data: HOME_SCREEN } },
    "/searchResult": { key: 'SearchResultScreen', pagePayload: { key: "SEARCH_RESULT", data: SEARCH_RESULT } },
    "/aboutUs": { key: 'AboutUsScreen', pagePayload: { key: "ABOUTUS_SCREEN", data: ABOUTUS_SCREEN } },
    "/blog": { key: 'BlogScreen', pagePayload: { key: "BLOG_SCREEN", data: BLOG_SCREEN } },
    "/:pid": { key: 'PropertyDetailScreen', pagePayload: { key: "CARD_DETAILS_SCREEN", data: CARD_DETAILS_SCREEN } },
    "/account/tabs": { key: 'AccountTabsScreen', pagePayload: { key: "ACCOUNT_TABS_SCREEN", data: ACCOUNT_TABS_SCREEN } },
    "/admin/form": { key: 'FormScreen', pagePayload: { key: "HOME_SCREEN", data: HOME_SCREEN } },
    "/admin/property": { key: 'PropertyManagementScreen', pagePayload: { key: "HOME_SCREEN", data: HOME_SCREEN } },
    "/admin/user": { key: 'UserManagementScreen', pagePayload: { key: "MANAGE_USER", data: MANAGE_USER } },
    "/admin/approveListing": { key: 'ApproveListingScreen', pagePayload: { key: "APPROVAL_PROPERTIES", data: APPROVAL_PROPERTIES } },
    "/admin/master": { key: 'MasterManagementScreen', pagePayload: { key: "HOME_SCREEN", data: HOME_SCREEN } },
    "/admin/masterTable": { key: 'MasterTableScreen', pagePayload: { key: "AD_MASTER_TABLE", data: AD_MASTER_TABLE } },
    "/admin/statistics": { key: 'StatsScreen', pagePayload: { key: "STATS_LIST", data: STATS_LIST } },
    "/admin/statistics/listingData": { key: 'ViewListingScreen', pagePayload: { key: "VIEW_LISTING", data: VIEW_LISTING } },
    "/admin": { key: 'AdminHomeScreen', pagePayload: { key: "HOME_SCREEN", data: HOME_SCREEN } },
};


export const COMPONENTS = {
    [LOADING]: { name: "CircularProgress", path: "", import: `import CircularProgress from "@material-ui/core/CircularProgress/CircularProgress.js";` },
    [AUTO_FETCH_API]: { name: "AutoFetchApi", path: "", import: "" },
    [AUTO_FETCH_API_POST]: { name: "AutoFetchApi", path: "", import: "" },
    [AUTO_FETCH_API_USER]: { name: "ApiHandler", path: "", import: "" },
    [TITLE]: { name: "", path: "", import: "" },      // create component
    [CONTAINER]: { name: "RenderComponent", path: "", import: "" },    // call self
    [PANEL_HEADER]: { name: "PanelHeader", path: "", import: "" },
    [IMAGE_BANNER]: { name: "Banner", path: "", import: "" },
    [SELECT]: { name: "SelectButton", path: "", import: "" },
    [SELECT2]: { name: "DropSelect", path: "", import: "" },
    [SLIDER]: { name: "Slider", path: "", import: "" },
    [API_BUTTON]: { name: "ApiButton", path: "", import: "" },
    [HEADING]: { name: "Heading", path: "", import: "" },
    [API_HEADING]: { name: "DynamicHeading", path: "", import: "" },
    [LIST]: { name: "List", path: "", import: "" },
    [DYNAMIC_CARD_CONTAINER]: { name: "DynamicCardContainer", path: "", import: "" },
    [DETAILED_VIEW]: { name: "DetailDataCard", path: "", import: "" },
    [NAVIGATE_BUTTON]: { name: "NavigateButton", path: "", import: "" },
    [PAGE_FOOTER]: { name: "Footer", path: "", import: "" },
    [PAGE_HEADER]: { name: "Header", path: "", import: "" },
    [OTP_LOGIN]: { name: "OtpLogin", path: "", import: "" },
    [HAMBURGER_MENU]: { name: "MenuState", path: "", import: "" },
    [TABS]: { name: "Tabbar", path: "", import: "" },
    [SELECT_SLIDER]: { name: "SelectSlider", path: "", import: "" },
    [TOGGLE_BUTTON]: { name: "CustomToogleButton", path: "", import: "" },
    [BUTTON]: { name: "Button", path: "", import: "" },
    [SCROLL_TO_TOP]: { name: "ScrollToTop", path: "", import: "" },
    [CHATBOT]: { name: "Chatbot", path: "", import: "" },
    [DASHBOARD_LISTING]: { name: "DashboardListing", path: "", import: "" },
    [ROUTE_BUTTON]: { name: "CustomRouteButton", path: "", import: "" },
    [LABEL_MAP]: { name: "LabelMap", path: "", import: "" },
    [HORIZONTAL_LINE]: { name: "Line", path: "", import: "" },     // create component
    [TABLE_HEADER]: { name: "TableHeader", path: "", import: "" },
    [LOGIN_REFRESH]: { name: "LoginRefresh", path: "", import: "" },
    [ABOUT_HERO]: { name: "AboutHero", path: "", import: "" },
    [CONTACT_US]: { name: "ContactForm", path: "", import: "" },
};
